name: DeathSwap
version: 1.0
author: InfinityMage
description: Swap places with another player every few minutes, and try to kill them!
main: club.infinitymage.deathswap.DeathSwap
api-version: 1.16
commands:
  deathswap:
